version: 0.2
env:
  secrets-manager:
    dockerHubUsername: dockerhub-login:krishna8750
    dockerHubPassword: dockerhub-login:Krishnateja8750!
phases:
  pre_build:
    commands:
      - 'docker login -u $dockerHubUsername -p $dockerHubPassword'
      - ls
